development:
  #slack_hook_url in ENV
  hangouts_redirection_url: "https://hangouts.google.com/call/pP-NIf4xLGPCAGE_rtKnAEEI"

test:
  slack_hook_url: "https://webhook.com/test"
  hangouts_redirection_url: "https://tests.com/config_redirect"

production:
  #slack_hook_url in ENV
  hangouts_redirection_url: "https://hangouts.google.com/call/pP-NIf4xLGPCAGE_rtKnAEEI"