development:
  adapter: postgresql
  encoding: unicode
  database: coffee_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: coffee_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: coffee_prod
  pool: 5
  username: postgres
  password: